version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch-node-browsers-legacy


    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      GRADLE_OPTS: -Xmx2000m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test